<?php

namespace OCA\AutomaticMediaEncoder\Constants;

class Formats
{
    public static function all()
    {
        return [
            [
                'extension' => '3dostr',
                'decode' => true,
                'encode' => false,
                'label' => '3DO STR',
            ],
            [
                'extension' => '3g2',
                'decode' => true,
                'encode' => true,
                'label' => 'QuickTime / MOV',
            ],
            [
                'extension' => '3gp',
                'decode' => true,
                'encode' => true,
                'label' => 'QuickTime / MOV',
            ],
            [
                'extension' => '4xm',
                'decode' => true,
                'encode' => false,
                'label' => '4X Technologies',
            ],
            [
                'extension' => 'a64',
                'decode' => false,
                'encode' => true,
                'label' => 'a64 - video for Commodore 64',
            ],
            [
                'extension' => 'aa',
                'decode' => true,
                'encode' => false,
                'label' => 'Audible AA format files',
            ],
            [
                'extension' => 'aac',
                'decode' => true,
                'encode' => false,
                'label' => 'raw ADTS AAC (Advanced Audio Coding)',
            ],
            [
                'extension' => 'ac3',
                'decode' => true,
                'encode' => true,
                'label' => 'raw AC-3',
            ],
            [
                'extension' => 'acm',
                'decode' => true,
                'encode' => false,
                'label' => 'Interplay ACM',
            ],
            [
                'extension' => 'act',
                'decode' => true,
                'encode' => false,
                'label' => 'ACT Voice file format',
            ],
            [
                'extension' => 'adf',
                'decode' => true,
                'encode' => false,
                'label' => 'Artworx Data Format',
            ],
            [
                'extension' => 'adp',
                'decode' => true,
                'encode' => false,
                'label' => 'ADP',
            ],
            [
                'extension' => 'ads',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony PS2 ADS',
            ],
            [
                'extension' => 'adts',
                'decode' => false,
                'encode' => true,
                'label' => 'ADTS AAC (Advanced Audio Coding)',
            ],
            [
                'extension' => 'adx',
                'decode' => true,
                'encode' => true,
                'label' => 'CRI ADX',
            ],
            [
                'extension' => 'aea',
                'decode' => true,
                'encode' => false,
                'label' => 'MD STUDIO audio',
            ],
            [
                'extension' => 'afc',
                'decode' => true,
                'encode' => false,
                'label' => 'AFC',
            ],
            [
                'extension' => 'aiff',
                'decode' => true,
                'encode' => true,
                'label' => 'Audio IFF',
            ],
            [
                'extension' => 'aix',
                'decode' => true,
                'encode' => false,
                'label' => 'CRI AIX',
            ],
            [
                'extension' => 'alaw',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM A-law',
            ],
            [
                'extension' => 'alias_pix',
                'decode' => true,
                'encode' => false,
                'label' => 'Alias/Wavefront PIX image',
            ],
            [
                'extension' => 'alsa',
                'decode' => true,
                'encode' => true,
                'label' => 'ALSA audio output',
            ],
            [
                'extension' => 'amr',
                'decode' => true,
                'encode' => true,
                'label' => '3GPP AMR',
            ],
            [
                'extension' => 'amrnb',
                'decode' => true,
                'encode' => false,
                'label' => 'raw AMR-NB',
            ],
            [
                'extension' => 'amrwb',
                'decode' => true,
                'encode' => false,
                'label' => 'raw AMR-WB',
            ],
            [
                'extension' => 'anm',
                'decode' => true,
                'encode' => false,
                'label' => 'Deluxe Paint Animation',
            ],
            [
                'extension' => 'apc',
                'decode' => true,
                'encode' => false,
                'label' => 'CRYO APC',
            ],
            [
                'extension' => 'ape',
                'decode' => true,
                'encode' => false,
                'label' => 'Monkey\'s Audio',
            ],
            [
                'extension' => 'apng',
                'decode' => true,
                'encode' => true,
                'label' => 'Animated Portable Network Graphics',
            ],
            [
                'extension' => 'aptx',
                'decode' => true,
                'encode' => true,
                'label' => 'raw aptX (Audio Processing Technology for Bluetooth)',
            ],
            [
                'extension' => 'aptx_hd',
                'decode' => true,
                'encode' => true,
                'label' => 'raw aptX HD (Audio Processing Technology for Bluetooth)',
            ],
            [
                'extension' => 'aqtitle',
                'decode' => true,
                'encode' => false,
                'label' => 'AQTitle subtitles',
            ],
            [
                'extension' => 'asf',
                'decode' => true,
                'encode' => true,
                'label' => 'ASF (Advanced / Active Streaming Format)',
            ],
            [
                'extension' => 'asf_o',
                'decode' => true,
                'encode' => false,
                'label' => 'ASF (Advanced / Active Streaming Format)',
            ],
            [
                'extension' => 'asf_stream',
                'decode' => false,
                'encode' => true,
                'label' => 'ASF (Advanced / Active Streaming Format)',
            ],
            [
                'extension' => 'ass',
                'decode' => true,
                'encode' => true,
                'label' => 'SSA (SubStation Alpha) subtitle',
            ],
            [
                'extension' => 'ast',
                'decode' => true,
                'encode' => true,
                'label' => 'AST (Audio Stream)',
            ],
            [
                'extension' => 'au',
                'decode' => true,
                'encode' => true,
                'label' => 'Sun AU',
            ],
            [
                'extension' => 'avi',
                'decode' => true,
                'encode' => true,
                'label' => 'AVI (Audio Video Interleaved)',
            ],
            [
                'extension' => 'avisynth',
                'decode' => true,
                'encode' => false,
                'label' => 'AviSynth script',
            ],
            [
                'extension' => 'avm2',
                'decode' => false,
                'encode' => true,
                'label' => 'SWF (ShockWave Flash) (AVM2)',
            ],
            [
                'extension' => 'avr',
                'decode' => true,
                'encode' => false,
                'label' => 'AVR (Audio Visual Research)',
            ],
            [
                'extension' => 'avs',
                'decode' => true,
                'encode' => false,
                'label' => 'Argonaut Games Creature Shock',
            ],
            [
                'extension' => 'avs2',
                'decode' => true,
                'encode' => true,
                'label' => 'raw AVS2-P2/IEEE1857.4 video',
            ],
            [
                'extension' => 'bethsoftvid',
                'decode' => true,
                'encode' => false,
                'label' => 'Bethesda Softworks VID',
            ],
            [
                'extension' => 'bfi',
                'decode' => true,
                'encode' => false,
                'label' => 'Brute Force & Ignorance',
            ],
            [
                'extension' => 'bfstm',
                'decode' => true,
                'encode' => false,
                'label' => 'BFSTM (Binary Cafe Stream)',
            ],
            [
                'extension' => 'bin',
                'decode' => true,
                'encode' => false,
                'label' => 'Binary text',
            ],
            [
                'extension' => 'bink',
                'decode' => true,
                'encode' => false,
                'label' => 'Bink',
            ],
            [
                'extension' => 'bit',
                'decode' => true,
                'encode' => true,
                'label' => 'G.729 BIT file format',
            ],
            [
                'extension' => 'bmp_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped bmp sequence',
            ],
            [
                'extension' => 'bmv',
                'decode' => true,
                'encode' => false,
                'label' => 'Discworld II BMV',
            ],
            [
                'extension' => 'boa',
                'decode' => true,
                'encode' => false,
                'label' => 'Black Ops Audio',
            ],
            [
                'extension' => 'brender_pix',
                'decode' => true,
                'encode' => false,
                'label' => 'BRender PIX image',
            ],
            [
                'extension' => 'brstm',
                'decode' => true,
                'encode' => false,
                'label' => 'BRSTM (Binary Revolution Stream)',
            ],
            [
                'extension' => 'c93',
                'decode' => true,
                'encode' => false,
                'label' => 'Interplay C93',
            ],
            [
                'extension' => 'caca',
                'decode' => false,
                'encode' => true,
                'label' => 'caca (color ASCII art) output device',
            ],
            [
                'extension' => 'caf',
                'decode' => true,
                'encode' => true,
                'label' => 'Apple CAF (Core Audio Format)',
            ],
            [
                'extension' => 'cavsvideo',
                'decode' => true,
                'encode' => true,
                'label' => 'raw Chinese AVS (Audio Video Standard) video',
            ],
            [
                'extension' => 'cdg',
                'decode' => true,
                'encode' => false,
                'label' => 'CD Graphics',
            ],
            [
                'extension' => 'cdxl',
                'decode' => true,
                'encode' => false,
                'label' => 'Commodore CDXL video',
            ],
            [
                'extension' => 'chromaprint',
                'decode' => false,
                'encode' => true,
                'label' => 'Chromaprint',
            ],
            [
                'extension' => 'cine',
                'decode' => true,
                'encode' => false,
                'label' => 'Phantom Cine',
            ],
            [
                'extension' => 'codec2',
                'decode' => true,
                'encode' => true,
                'label' => 'codec2 .c2 muxer',
            ],
            [
                'extension' => 'codec2raw',
                'decode' => true,
                'encode' => true,
                'label' => 'raw codec2 muxer',
            ],
            [
                'extension' => 'concat',
                'decode' => true,
                'encode' => false,
                'label' => 'Virtual concatenation script',
            ],
            [
                'extension' => 'crc',
                'decode' => false,
                'encode' => true,
                'label' => 'CRC testing',
            ],
            [
                'extension' => 'dash',
                'decode' => true,
                'encode' => true,
                'label' => 'DASH Muxer',
            ],
            [
                'extension' => 'data',
                'decode' => true,
                'encode' => true,
                'label' => 'raw data',
            ],
            [
                'extension' => 'daud',
                'decode' => true,
                'encode' => true,
                'label' => 'D-Cinema audio',
            ],
            [
                'extension' => 'dcstr',
                'decode' => true,
                'encode' => false,
                'label' => 'Sega DC STR',
            ],
            [
                'extension' => 'dds_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped dds sequence',
            ],
            [
                'extension' => 'dfa',
                'decode' => true,
                'encode' => false,
                'label' => 'Chronomaster DFA',
            ],
            [
                'extension' => 'dhav',
                'decode' => true,
                'encode' => false,
                'label' => 'Video DAV',
            ],
            [
                'extension' => 'dirac',
                'decode' => true,
                'encode' => true,
                'label' => 'raw Dirac',
            ],
            [
                'extension' => 'dnxhd',
                'decode' => true,
                'encode' => true,
                'label' => 'raw DNxHD (SMPTE VC-3)',
            ],
            [
                'extension' => 'dpx_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped dpx sequence',
            ],
            [
                'extension' => 'dsf',
                'decode' => true,
                'encode' => false,
                'label' => 'DSD Stream File (DSF)',
            ],
            [
                'extension' => 'dsicin',
                'decode' => true,
                'encode' => false,
                'label' => 'Delphine Software International CIN',
            ],
            [
                'extension' => 'dss',
                'decode' => true,
                'encode' => false,
                'label' => 'Digital Speech Standard (DSS)',
            ],
            [
                'extension' => 'dts',
                'decode' => true,
                'encode' => true,
                'label' => 'raw DTS',
            ],
            [
                'extension' => 'dtshd',
                'decode' => true,
                'encode' => false,
                'label' => 'raw DTS-HD',
            ],
            [
                'extension' => 'dv',
                'decode' => true,
                'encode' => true,
                'label' => 'DV (Digital Video)',
            ],
            [
                'extension' => 'dvbsub',
                'decode' => true,
                'encode' => false,
                'label' => 'raw dvbsub',
            ],
            [
                'extension' => 'dvbtxt',
                'decode' => true,
                'encode' => false,
                'label' => 'dvbtxt',
            ],
            [
                'extension' => 'dvd',
                'decode' => false,
                'encode' => true,
                'label' => 'MPEG-2 PS (DVD VOB)',
            ],
            [
                'extension' => 'dxa',
                'decode' => true,
                'encode' => false,
                'label' => 'DXA',
            ],
            [
                'extension' => 'ea',
                'decode' => true,
                'encode' => false,
                'label' => 'Electronic Arts Multimedia',
            ],
            [
                'extension' => 'ea_cdata',
                'decode' => true,
                'encode' => false,
                'label' => 'Electronic Arts cdata',
            ],
            [
                'extension' => 'eac3',
                'decode' => true,
                'encode' => true,
                'label' => 'raw E-AC-3',
            ],
            [
                'extension' => 'epaf',
                'decode' => true,
                'encode' => false,
                'label' => 'Ensoniq Paris Audio File',
            ],
            [
                'extension' => 'exr_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped exr sequence',
            ],
            [
                'extension' => 'f32be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM 32-bit floating-point big-endian',
            ],
            [
                'extension' => 'f32le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM 32-bit floating-point little-endian',
            ],
            [
                'extension' => 'f4v',
                'decode' => false,
                'encode' => true,
                'label' => 'F4V Adobe Flash Video',
            ],
            [
                'extension' => 'f64be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM 64-bit floating-point big-endian',
            ],
            [
                'extension' => 'f64le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM 64-bit floating-point little-endian',
            ],
            [
                'extension' => 'fbdev',
                'decode' => true,
                'encode' => true,
                'label' => 'Linux framebuffer',
            ],
            [
                'extension' => 'ffmetadata',
                'decode' => true,
                'encode' => true,
                'label' => 'FFmpeg metadata in text',
            ],
            [
                'extension' => 'fifo',
                'decode' => false,
                'encode' => true,
                'label' => 'FIFO queue pseudo-muxer',
            ],
            [
                'extension' => 'fifo_test',
                'decode' => false,
                'encode' => true,
                'label' => 'Fifo test muxer',
            ],
            [
                'extension' => 'film_cpk',
                'decode' => true,
                'encode' => true,
                'label' => 'Sega FILM / CPK',
            ],
            [
                'extension' => 'filmstrip',
                'decode' => true,
                'encode' => true,
                'label' => 'Adobe Filmstrip',
            ],
            [
                'extension' => 'fits',
                'decode' => true,
                'encode' => true,
                'label' => 'Flexible Image Transport System',
            ],
            [
                'extension' => 'flac',
                'decode' => true,
                'encode' => true,
                'label' => 'raw FLAC',
            ],
            [
                'extension' => 'flic',
                'decode' => true,
                'encode' => false,
                'label' => 'FLI/FLC/FLX animation',
            ],
            [
                'extension' => 'flv',
                'decode' => true,
                'encode' => true,
                'label' => 'FLV (Flash Video)',
            ],
            [
                'extension' => 'framecrc',
                'decode' => false,
                'encode' => true,
                'label' => 'framecrc testing',
            ],
            [
                'extension' => 'framehash',
                'decode' => false,
                'encode' => true,
                'label' => 'Per-frame hash testing',
            ],
            [
                'extension' => 'framemd5',
                'decode' => false,
                'encode' => true,
                'label' => 'Per-frame MD5 testing',
            ],
            [
                'extension' => 'frm',
                'decode' => true,
                'encode' => false,
                'label' => 'Megalux Frame',
            ],
            [
                'extension' => 'fsb',
                'decode' => true,
                'encode' => false,
                'label' => 'FMOD Sample Bank',
            ],
            [
                'extension' => 'g722',
                'decode' => true,
                'encode' => true,
                'label' => 'raw G.722',
            ],
            [
                'extension' => 'g723_1',
                'decode' => true,
                'encode' => true,
                'label' => 'raw G.723.1',
            ],
            [
                'extension' => 'g726',
                'decode' => true,
                'encode' => true,
                'label' => 'raw big-endian G.726 ("left-justified")',
            ],
            [
                'extension' => 'g726le',
                'decode' => true,
                'encode' => true,
                'label' => 'raw little-endian G.726 ("right-justified")',
            ],
            [
                'extension' => 'g729',
                'decode' => true,
                'encode' => false,
                'label' => 'G.729 raw format demuxer',
            ],
            [
                'extension' => 'gdv',
                'decode' => true,
                'encode' => false,
                'label' => 'Gremlin Digital Video',
            ],
            [
                'extension' => 'genh',
                'decode' => true,
                'encode' => false,
                'label' => 'GENeric Header',
            ],
            [
                'extension' => 'gif',
                'decode' => true,
                'encode' => true,
                'label' => 'CompuServe Graphics Interchange Format (GIF)',
            ],
            [
                'extension' => 'gif_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped gif sequence',
            ],
            [
                'extension' => 'gsm',
                'decode' => true,
                'encode' => true,
                'label' => 'raw GSM',
            ],
            [
                'extension' => 'gxf',
                'decode' => true,
                'encode' => true,
                'label' => 'GXF (General eXchange Format)',
            ],
            [
                'extension' => 'h261',
                'decode' => true,
                'encode' => true,
                'label' => 'raw H.261',
            ],
            [
                'extension' => 'h263',
                'decode' => true,
                'encode' => true,
                'label' => 'raw H.263',
            ],
            [
                'extension' => 'h264',
                'decode' => true,
                'encode' => true,
                'label' => 'raw H.264 video',
            ],
            [
                'extension' => 'hash',
                'decode' => false,
                'encode' => true,
                'label' => 'Hash testing',
            ],
            [
                'extension' => 'hcom',
                'decode' => true,
                'encode' => false,
                'label' => 'Macintosh HCOM',
            ],
            [
                'extension' => 'hds',
                'decode' => false,
                'encode' => true,
                'label' => 'HDS Muxer',
            ],
            [
                'extension' => 'hevc',
                'decode' => true,
                'encode' => true,
                'label' => 'raw HEVC video',
            ],
            [
                'extension' => 'hls',
                'decode' => true,
                'encode' => true,
                'label' => 'Apple HTTP Live Streaming',
            ],
            [
                'extension' => 'hnm',
                'decode' => true,
                'encode' => false,
                'label' => 'Cryo HNM v4',
            ],
            [
                'extension' => 'ico',
                'decode' => true,
                'encode' => true,
                'label' => 'Microsoft Windows ICO',
            ],
            [
                'extension' => 'idcin',
                'decode' => true,
                'encode' => false,
                'label' => 'id Cinematic',
            ],
            [
                'extension' => 'idf',
                'decode' => true,
                'encode' => false,
                'label' => 'iCE Draw File',
            ],
            [
                'extension' => 'iec61883',
                'decode' => true,
                'encode' => false,
                'label' => 'libiec61883 (new DV1394) A/V input device',
            ],
            [
                'extension' => 'iff',
                'decode' => true,
                'encode' => false,
                'label' => 'IFF (Interchange File Format)',
            ],
            [
                'extension' => 'ifv',
                'decode' => true,
                'encode' => false,
                'label' => 'IFV CCTV DVR',
            ],
            [
                'extension' => 'ilbc',
                'decode' => true,
                'encode' => true,
                'label' => 'iLBC storage',
            ],
            [
                'extension' => 'image2',
                'decode' => true,
                'encode' => true,
                'label' => 'image2 sequence',
            ],
            [
                'extension' => 'image2pipe',
                'decode' => true,
                'encode' => true,
                'label' => 'piped image2 sequence',
            ],
            [
                'extension' => 'ingenient',
                'decode' => true,
                'encode' => false,
                'label' => 'raw Ingenient MJPEG',
            ],
            [
                'extension' => 'ipmovie',
                'decode' => true,
                'encode' => false,
                'label' => 'Interplay MVE',
            ],
            [
                'extension' => 'ipod',
                'decode' => false,
                'encode' => true,
                'label' => 'iPod H.264 MP4 (MPEG-4 Part 14)',
            ],
            [
                'extension' => 'ircam',
                'decode' => true,
                'encode' => true,
                'label' => 'Berkeley/IRCAM/CARL Sound Format',
            ],
            [
                'extension' => 'ismv',
                'decode' => false,
                'encode' => true,
                'label' => 'ISMV/ISMA (Smooth Streaming)',
            ],
            [
                'extension' => 'iss',
                'decode' => true,
                'encode' => false,
                'label' => 'Funcom ISS',
            ],
            [
                'extension' => 'iv8',
                'decode' => true,
                'encode' => false,
                'label' => 'IndigoVision 8000 video',
            ],
            [
                'extension' => 'ivf',
                'decode' => true,
                'encode' => true,
                'label' => 'On2 IVF',
            ],
            [
                'extension' => 'ivr',
                'decode' => true,
                'encode' => false,
                'label' => 'IVR (Internet Video Recording)',
            ],
            [
                'extension' => 'j2k_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped j2k sequence',
            ],
            [
                'extension' => 'jack',
                'decode' => true,
                'encode' => false,
                'label' => 'JACK Audio Connection Kit',
            ],
            [
                'extension' => 'jacosub',
                'decode' => true,
                'encode' => true,
                'label' => 'JACOsub subtitle format',
            ],
            [
                'extension' => 'jpeg_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped jpeg sequence',
            ],
            [
                'extension' => 'jpegls_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped jpegls sequence',
            ],
            [
                'extension' => 'jv',
                'decode' => true,
                'encode' => false,
                'label' => 'Bitmap Brothers JV',
            ],
            [
                'extension' => 'kmsgrab',
                'decode' => true,
                'encode' => false,
                'label' => 'KMS screen capture',
            ],
            [
                'extension' => 'kux',
                'decode' => true,
                'encode' => false,
                'label' => 'KUX (YouKu)',
            ],
            [
                'extension' => 'latm',
                'decode' => false,
                'encode' => true,
                'label' => 'LOAS/LATM',
            ],
            [
                'extension' => 'lavfi',
                'decode' => true,
                'encode' => false,
                'label' => 'Libavfilter virtual input device',
            ],
            [
                'extension' => 'libdc1394',
                'decode' => true,
                'encode' => false,
                'label' => 'dc1394 v.2 A/V grab',
            ],
            [
                'extension' => 'libgme',
                'decode' => true,
                'encode' => false,
                'label' => 'Game Music Emu demuxer',
            ],
            [
                'extension' => 'libopenmpt',
                'decode' => true,
                'encode' => false,
                'label' => 'Tracker formats (libopenmpt)',
            ],
            [
                'extension' => 'live_flv',
                'decode' => true,
                'encode' => false,
                'label' => 'live RTMP FLV (Flash Video)',
            ],
            [
                'extension' => 'lmlm4',
                'decode' => true,
                'encode' => false,
                'label' => 'raw lmlm4',
            ],
            [
                'extension' => 'loas',
                'decode' => true,
                'encode' => false,
                'label' => 'LOAS AudioSyncStream',
            ],
            [
                'extension' => 'lrc',
                'decode' => true,
                'encode' => true,
                'label' => 'LRC lyrics',
            ],
            [
                'extension' => 'lvf',
                'decode' => true,
                'encode' => false,
                'label' => 'LVF',
            ],
            [
                'extension' => 'lxf',
                'decode' => true,
                'encode' => false,
                'label' => 'VR native stream (LXF)',
            ],
            [
                'extension' => 'm4a',
                'decode' => true,
                'encode' => false,
                'label' => 'QuickTime / MOV',
            ],
            [
                'extension' => 'm4v',
                'decode' => true,
                'encode' => true,
                'label' => 'raw MPEG-4 video',
            ],
            [
                'extension' => 'matroska',
                'decode' => true,
                'encode' => true,
                'label' => 'Matroska / WebM',
            ],
            [
                'extension' => 'md5',
                'decode' => false,
                'encode' => true,
                'label' => 'MD5 testing',
            ],
            [
                'extension' => 'mgsts',
                'decode' => true,
                'encode' => false,
                'label' => 'Metal Gear Solid: The Twin Snakes',
            ],
            [
                'extension' => 'microdvd',
                'decode' => true,
                'encode' => true,
                'label' => 'MicroDVD subtitle format',
            ],
            [
                'extension' => 'mj2',
                'decode' => true,
                'encode' => false,
                'label' => 'QuickTime / MOV',
            ],
            [
                'extension' => 'mjpeg',
                'decode' => true,
                'encode' => true,
                'label' => 'raw MJPEG video',
            ],
            [
                'extension' => 'mjpeg_2000',
                'decode' => true,
                'encode' => false,
                'label' => 'raw MJPEG 2000 video',
            ],
            [
                'extension' => 'mkvtimestamp_v2',
                'decode' => false,
                'encode' => true,
                'label' => 'extract pts as timecode v2 format, as defined by mkvtoolnix',
            ],
            [
                'extension' => 'mlp',
                'decode' => true,
                'encode' => true,
                'label' => 'raw MLP',
            ],
            [
                'extension' => 'mlv',
                'decode' => true,
                'encode' => false,
                'label' => 'Magic Lantern Video (MLV)',
            ],
            [
                'extension' => 'mm',
                'decode' => true,
                'encode' => false,
                'label' => 'American Laser Games MM',
            ],
            [
                'extension' => 'mmf',
                'decode' => true,
                'encode' => true,
                'label' => 'Yamaha SMAF',
            ],
            [
                'extension' => 'mov',
                'decode' => true,
                'encode' => true,
                'label' => 'QuickTime / MOV',
            ],
            [
                'extension' => 'mp2',
                'decode' => false,
                'encode' => true,
                'label' => 'MP2 (MPEG audio layer 2)',
            ],
            [
                'extension' => 'mp3',
                'decode' => true,
                'encode' => true,
                'label' => 'MP3 (MPEG audio layer 3)',
            ],
            [
                'extension' => 'mp4',
                'decode' => true,
                'encode' => true,
                'label' => 'MP4 (MPEG-4 Part 14)',
            ],
            [
                'extension' => 'mpc',
                'decode' => true,
                'encode' => false,
                'label' => 'Musepack',
            ],
            [
                'extension' => 'mpc8',
                'decode' => true,
                'encode' => false,
                'label' => 'Musepack SV8',
            ],
            [
                'extension' => 'mpeg',
                'decode' => true,
                'encode' => true,
                'label' => 'MPEG-1 Systems / MPEG program stream',
            ],
            [
                'extension' => 'mpeg1video',
                'decode' => false,
                'encode' => true,
                'label' => 'raw MPEG-1 video',
            ],
            [
                'extension' => 'mpeg2video',
                'decode' => false,
                'encode' => true,
                'label' => 'raw MPEG-2 video',
            ],
            [
                'extension' => 'mpegts',
                'decode' => true,
                'encode' => true,
                'label' => 'MPEG-TS (MPEG-2 Transport Stream)',
            ],
            [
                'extension' => 'mpegtsraw',
                'decode' => true,
                'encode' => false,
                'label' => 'raw MPEG-TS (MPEG-2 Transport Stream)',
            ],
            [
                'extension' => 'mpegvideo',
                'decode' => true,
                'encode' => false,
                'label' => 'raw MPEG video',
            ],
            [
                'extension' => 'mpjpeg',
                'decode' => true,
                'encode' => true,
                'label' => 'MIME multipart JPEG',
            ],
            [
                'extension' => 'mpl2',
                'decode' => true,
                'encode' => false,
                'label' => 'MPL2 subtitles',
            ],
            [
                'extension' => 'mpsub',
                'decode' => true,
                'encode' => false,
                'label' => 'MPlayer subtitles',
            ],
            [
                'extension' => 'msf',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony PS3 MSF',
            ],
            [
                'extension' => 'msnwctcp',
                'decode' => true,
                'encode' => false,
                'label' => 'MSN TCP Webcam stream',
            ],
            [
                'extension' => 'mtaf',
                'decode' => true,
                'encode' => false,
                'label' => 'Konami PS2 MTAF',
            ],
            [
                'extension' => 'mtv',
                'decode' => true,
                'encode' => false,
                'label' => 'MTV',
            ],
            [
                'extension' => 'mulaw',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM mu-law',
            ],
            [
                'extension' => 'musx',
                'decode' => true,
                'encode' => false,
                'label' => 'Eurocom MUSX',
            ],
            [
                'extension' => 'mv',
                'decode' => true,
                'encode' => false,
                'label' => 'Silicon Graphics Movie',
            ],
            [
                'extension' => 'mvi',
                'decode' => true,
                'encode' => false,
                'label' => 'Motion Pixels MVI',
            ],
            [
                'extension' => 'mxf',
                'decode' => true,
                'encode' => true,
                'label' => 'MXF (Material eXchange Format)',
            ],
            [
                'extension' => 'mxf_d10',
                'decode' => false,
                'encode' => true,
                'label' => 'MXF (Material eXchange Format) D-10 Mapping',
            ],
            [
                'extension' => 'mxf_opatom',
                'decode' => false,
                'encode' => true,
                'label' => 'MXF (Material eXchange Format) Operational Pattern Atom',
            ],
            [
                'extension' => 'mxg',
                'decode' => true,
                'encode' => false,
                'label' => 'MxPEG clip',
            ],
            [
                'extension' => 'nc',
                'decode' => true,
                'encode' => false,
                'label' => 'NC camera feed',
            ],
            [
                'extension' => 'nistsphere',
                'decode' => true,
                'encode' => false,
                'label' => 'NIST SPeech HEader REsources',
            ],
            [
                'extension' => 'nsp',
                'decode' => true,
                'encode' => false,
                'label' => 'Computerized Speech Lab NSP',
            ],
            [
                'extension' => 'nsv',
                'decode' => true,
                'encode' => false,
                'label' => 'Nullsoft Streaming Video',
            ],
            [
                'extension' => 'null',
                'decode' => false,
                'encode' => true,
                'label' => 'raw null video',
            ],
            [
                'extension' => 'nut',
                'decode' => true,
                'encode' => true,
                'label' => 'NUT',
            ],
            [
                'extension' => 'nuv',
                'decode' => true,
                'encode' => false,
                'label' => 'NuppelVideo',
            ],
            [
                'extension' => 'oga',
                'decode' => false,
                'encode' => true,
                'label' => 'Ogg Audio',
            ],
            [
                'extension' => 'ogg',
                'decode' => true,
                'encode' => true,
                'label' => 'Ogg',
            ],
            [
                'extension' => 'ogv',
                'decode' => false,
                'encode' => true,
                'label' => 'Ogg Video',
            ],
            [
                'extension' => 'oma',
                'decode' => true,
                'encode' => true,
                'label' => 'Sony OpenMG audio',
            ],
            [
                'extension' => 'openal',
                'decode' => true,
                'encode' => false,
                'label' => 'OpenAL audio capture device',
            ],
            [
                'extension' => 'opengl',
                'decode' => false,
                'encode' => true,
                'label' => 'OpenGL output',
            ],
            [
                'extension' => 'opus',
                'decode' => false,
                'encode' => true,
                'label' => 'Ogg Opus',
            ],
            [
                'extension' => 'oss',
                'decode' => true,
                'encode' => true,
                'label' => 'OSS (Open Sound System) playback',
            ],
            [
                'extension' => 'paf',
                'decode' => true,
                'encode' => false,
                'label' => 'Amazing Studio Packed Animation File',
            ],
            [
                'extension' => 'pam_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pam sequence',
            ],
            [
                'extension' => 'pbm_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pbm sequence',
            ],
            [
                'extension' => 'pcx_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pcx sequence',
            ],
            [
                'extension' => 'pgm_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pgm sequence',
            ],
            [
                'extension' => 'pgmyuv_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pgmyuv sequence',
            ],
            [
                'extension' => 'pictor_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped pictor sequence',
            ],
            [
                'extension' => 'pjs',
                'decode' => true,
                'encode' => false,
                'label' => 'PJS (Phoenix Japanimation Society) subtitles',
            ],
            [
                'extension' => 'pmp',
                'decode' => true,
                'encode' => false,
                'label' => 'Playstation Portable PMP',
            ],
            [
                'extension' => 'png_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped png sequence',
            ],
            [
                'extension' => 'ppm_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped ppm sequence',
            ],
            [
                'extension' => 'psd_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped psd sequence',
            ],
            [
                'extension' => 'psp',
                'decode' => false,
                'encode' => true,
                'label' => 'PSP MP4 (MPEG-4 Part 14)',
            ],
            [
                'extension' => 'psxstr',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony Playstation STR',
            ],
            [
                'extension' => 'pulse',
                'decode' => true,
                'encode' => true,
                'label' => 'Pulse audio output',
            ],
            [
                'extension' => 'pva',
                'decode' => true,
                'encode' => false,
                'label' => 'TechnoTrend PVA',
            ],
            [
                'extension' => 'pvf',
                'decode' => true,
                'encode' => false,
                'label' => 'PVF (Portable Voice Format)',
            ],
            [
                'extension' => 'qcp',
                'decode' => true,
                'encode' => false,
                'label' => 'QCP',
            ],
            [
                'extension' => 'qdraw_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped qdraw sequence',
            ],
            [
                'extension' => 'r3d',
                'decode' => true,
                'encode' => false,
                'label' => 'REDCODE R3D',
            ],
            [
                'extension' => 'rawvideo',
                'decode' => true,
                'encode' => true,
                'label' => 'raw video',
            ],
            [
                'extension' => 'realtext',
                'decode' => true,
                'encode' => false,
                'label' => 'RealText subtitle format',
            ],
            [
                'extension' => 'redspark',
                'decode' => true,
                'encode' => false,
                'label' => 'RedSpark',
            ],
            [
                'extension' => 'rl2',
                'decode' => true,
                'encode' => false,
                'label' => 'RL2',
            ],
            [
                'extension' => 'rm',
                'decode' => true,
                'encode' => true,
                'label' => 'RealMedia',
            ],
            [
                'extension' => 'roq',
                'decode' => true,
                'encode' => true,
                'label' => 'raw id RoQ',
            ],
            [
                'extension' => 'rpl',
                'decode' => true,
                'encode' => false,
                'label' => 'RPL / ARMovie',
            ],
            [
                'extension' => 'rsd',
                'decode' => true,
                'encode' => false,
                'label' => 'GameCube RSD',
            ],
            [
                'extension' => 'rso',
                'decode' => true,
                'encode' => true,
                'label' => 'Lego Mindstorms RSO',
            ],
            [
                'extension' => 'rtp',
                'decode' => true,
                'encode' => true,
                'label' => 'RTP output',
            ],
            [
                'extension' => 'rtp_mpegts',
                'decode' => false,
                'encode' => true,
                'label' => 'RTP/mpegts output format',
            ],
            [
                'extension' => 'rtsp',
                'decode' => true,
                'encode' => true,
                'label' => 'RTSP output',
            ],
            [
                'extension' => 's16be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 16-bit big-endian',
            ],
            [
                'extension' => 's16le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 16-bit little-endian',
            ],
            [
                'extension' => 's24be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 24-bit big-endian',
            ],
            [
                'extension' => 's24le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 24-bit little-endian',
            ],
            [
                'extension' => 's32be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 32-bit big-endian',
            ],
            [
                'extension' => 's32le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 32-bit little-endian',
            ],
            [
                'extension' => 's337m',
                'decode' => true,
                'encode' => false,
                'label' => 'SMPTE 337M',
            ],
            [
                'extension' => 's8',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM signed 8-bit',
            ],
            [
                'extension' => 'sami',
                'decode' => true,
                'encode' => false,
                'label' => 'SAMI subtitle format',
            ],
            [
                'extension' => 'sap',
                'decode' => true,
                'encode' => true,
                'label' => 'SAP output',
            ],
            [
                'extension' => 'sbc',
                'decode' => true,
                'encode' => true,
                'label' => 'raw SBC',
            ],
            [
                'extension' => 'sbg',
                'decode' => true,
                'encode' => false,
                'label' => 'SBaGen binaural beats script',
            ],
            [
                'extension' => 'scc',
                'decode' => true,
                'encode' => true,
                'label' => 'Scenarist Closed Captions',
            ],
            [
                'extension' => 'sdl',
                'decode' => false,
                'encode' => true,
                'label' => 'SDL2 output device',
            ],
            [
                'extension' => 'sdl2',
                'decode' => false,
                'encode' => true,
                'label' => 'SDL2 output device',
            ],
            [
                'extension' => 'sdp',
                'decode' => true,
                'encode' => false,
                'label' => 'SDP',
            ],
            [
                'extension' => 'sdr2',
                'decode' => true,
                'encode' => false,
                'label' => 'SDR2',
            ],
            [
                'extension' => 'sds',
                'decode' => true,
                'encode' => false,
                'label' => 'MIDI Sample Dump Standard',
            ],
            [
                'extension' => 'sdx',
                'decode' => true,
                'encode' => false,
                'label' => 'Sample Dump eXchange',
            ],
            [
                'extension' => 'segment',
                'decode' => false,
                'encode' => true,
                'label' => 'segment',
            ],
            [
                'extension' => 'ser',
                'decode' => true,
                'encode' => false,
                'label' => 'SER (Simple uncompressed video format for astronomical capturing)',
            ],
            [
                'extension' => 'sgi_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped sgi sequence',
            ],
            [
                'extension' => 'shn',
                'decode' => true,
                'encode' => false,
                'label' => 'raw Shorten',
            ],
            [
                'extension' => 'siff',
                'decode' => true,
                'encode' => false,
                'label' => 'Beam Software SIFF',
            ],
            [
                'extension' => 'singlejpeg',
                'decode' => false,
                'encode' => true,
                'label' => 'JPEG single image',
            ],
            [
                'extension' => 'sln',
                'decode' => true,
                'encode' => false,
                'label' => 'Asterisk raw pcm',
            ],
            [
                'extension' => 'smjpeg',
                'decode' => true,
                'encode' => true,
                'label' => 'Loki SDL MJPEG',
            ],
            [
                'extension' => 'smk',
                'decode' => true,
                'encode' => false,
                'label' => 'Smacker',
            ],
            [
                'extension' => 'smoothstreaming',
                'decode' => false,
                'encode' => true,
                'label' => 'Smooth Streaming Muxer',
            ],
            [
                'extension' => 'smush',
                'decode' => true,
                'encode' => false,
                'label' => 'LucasArts Smush',
            ],
            [
                'extension' => 'sndio',
                'decode' => true,
                'encode' => true,
                'label' => 'sndio audio playback',
            ],
            [
                'extension' => 'sol',
                'decode' => true,
                'encode' => false,
                'label' => 'Sierra SOL',
            ],
            [
                'extension' => 'sox',
                'decode' => true,
                'encode' => true,
                'label' => 'SoX native',
            ],
            [
                'extension' => 'spdif',
                'decode' => true,
                'encode' => true,
                'label' => 'IEC 61937 (used on S/PDIF - IEC958)',
            ],
            [
                'extension' => 'spx',
                'decode' => false,
                'encode' => true,
                'label' => 'Ogg Speex',
            ],
            [
                'extension' => 'srt',
                'decode' => true,
                'encode' => true,
                'label' => 'SubRip subtitle',
            ],
            [
                'extension' => 'ssegment',
                'decode' => false,
                'encode' => true,
                'label' => 'streaming segment muxer',
            ],
            [
                'extension' => 'stl',
                'decode' => true,
                'encode' => false,
                'label' => 'Spruce subtitle format',
            ],
            [
                'extension' => 'stream_segment',
                'decode' => false,
                'encode' => true,
                'label' => 'streaming segment muxer',
            ],
            [
                'extension' => 'subviewer',
                'decode' => true,
                'encode' => false,
                'label' => 'SubViewer subtitle format',
            ],
            [
                'extension' => 'subviewer1',
                'decode' => true,
                'encode' => false,
                'label' => 'SubViewer v1 subtitle format',
            ],
            [
                'extension' => 'sunrast_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped sunrast sequence',
            ],
            [
                'extension' => 'sup',
                'decode' => true,
                'encode' => true,
                'label' => 'raw HDMV Presentation Graphic Stream subtitles',
            ],
            [
                'extension' => 'svag',
                'decode' => true,
                'encode' => false,
                'label' => 'Konami PS2 SVAG',
            ],
            [
                'extension' => 'svcd',
                'decode' => false,
                'encode' => true,
                'label' => 'MPEG-2 PS (SVCD)',
            ],
            [
                'extension' => 'svg_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped svg sequence',
            ],
            [
                'extension' => 'swf',
                'decode' => true,
                'encode' => true,
                'label' => 'SWF (ShockWave Flash)',
            ],
            [
                'extension' => 'tak',
                'decode' => true,
                'encode' => false,
                'label' => 'raw TAK',
            ],
            [
                'extension' => 'tedcaptions',
                'decode' => true,
                'encode' => false,
                'label' => 'TED Talks captions',
            ],
            [
                'extension' => 'tee',
                'decode' => false,
                'encode' => true,
                'label' => 'Multiple muxer tee',
            ],
            [
                'extension' => 'thp',
                'decode' => true,
                'encode' => false,
                'label' => 'THP',
            ],
            [
                'extension' => 'tiertexseq',
                'decode' => true,
                'encode' => false,
                'label' => 'Tiertex Limited SEQ',
            ],
            [
                'extension' => 'tiff_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped tiff sequence',
            ],
            [
                'extension' => 'tmv',
                'decode' => true,
                'encode' => false,
                'label' => '8088flex TMV',
            ],
            [
                'extension' => 'truehd',
                'decode' => true,
                'encode' => true,
                'label' => 'raw TrueHD',
            ],
            [
                'extension' => 'tta',
                'decode' => true,
                'encode' => true,
                'label' => 'TTA (True Audio)',
            ],
            [
                'extension' => 'tty',
                'decode' => true,
                'encode' => false,
                'label' => 'Tele-typewriter',
            ],
            [
                'extension' => 'txd',
                'decode' => true,
                'encode' => false,
                'label' => 'Renderware TeXture Dictionary',
            ],
            [
                'extension' => 'ty',
                'decode' => true,
                'encode' => false,
                'label' => 'TiVo TY Stream',
            ],
            [
                'extension' => 'u16be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 16-bit big-endian',
            ],
            [
                'extension' => 'u16le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 16-bit little-endian',
            ],
            [
                'extension' => 'u24be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 24-bit big-endian',
            ],
            [
                'extension' => 'u24le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 24-bit little-endian',
            ],
            [
                'extension' => 'u32be',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 32-bit big-endian',
            ],
            [
                'extension' => 'u32le',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 32-bit little-endian',
            ],
            [
                'extension' => 'u8',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM unsigned 8-bit',
            ],
            [
                'extension' => 'uncodedframecrc',
                'decode' => false,
                'encode' => true,
                'label' => 'uncoded framecrc testing',
            ],
            [
                'extension' => 'v210',
                'decode' => true,
                'encode' => false,
                'label' => 'Uncompressed 4:2:2 10-bit',
            ],
            [
                'extension' => 'v210x',
                'decode' => true,
                'encode' => false,
                'label' => 'Uncompressed 4:2:2 10-bit',
            ],
            [
                'extension' => 'v4l2',
                'decode' => true,
                'encode' => true,
                'label' => 'Video4Linux2 output device',
            ],
            [
                'extension' => 'vag',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony PS2 VAG',
            ],
            [
                'extension' => 'vc1',
                'decode' => true,
                'encode' => true,
                'label' => 'raw VC-1 video',
            ],
            [
                'extension' => 'vc1test',
                'decode' => true,
                'encode' => true,
                'label' => 'VC-1 test bitstream',
            ],
            [
                'extension' => 'vcd',
                'decode' => false,
                'encode' => true,
                'label' => 'MPEG-1 Systems / MPEG program stream (VCD)',
            ],
            [
                'extension' => 'vidc',
                'decode' => true,
                'encode' => true,
                'label' => 'PCM Archimedes VIDC',
            ],
            [
                'extension' => 'video4linux2',
                'decode' => true,
                'encode' => true,
                'label' => 'Video4Linux2 output device',
            ],
            [
                'extension' => 'vividas',
                'decode' => true,
                'encode' => false,
                'label' => 'Vividas VIV',
            ],
            [
                'extension' => 'vivo',
                'decode' => true,
                'encode' => false,
                'label' => 'Vivo',
            ],
            [
                'extension' => 'vmd',
                'decode' => true,
                'encode' => false,
                'label' => 'Sierra VMD',
            ],
            [
                'extension' => 'vob',
                'decode' => false,
                'encode' => true,
                'label' => 'MPEG-2 PS (VOB)',
            ],
            [
                'extension' => 'vobsub',
                'decode' => true,
                'encode' => false,
                'label' => 'VobSub subtitle format',
            ],
            [
                'extension' => 'voc',
                'decode' => true,
                'encode' => true,
                'label' => 'Creative Voice',
            ],
            [
                'extension' => 'vpk',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony PS2 VPK',
            ],
            [
                'extension' => 'vplayer',
                'decode' => true,
                'encode' => false,
                'label' => 'VPlayer subtitles',
            ],
            [
                'extension' => 'vqf',
                'decode' => true,
                'encode' => false,
                'label' => 'Nippon Telegraph and Telephone Corporation (NTT) TwinVQ',
            ],
            [
                'extension' => 'w64',
                'decode' => true,
                'encode' => true,
                'label' => 'Sony Wave64',
            ],
            [
                'extension' => 'wav',
                'decode' => true,
                'encode' => true,
                'label' => 'WAV / WAVE (Waveform Audio)',
            ],
            [
                'extension' => 'wc3movie',
                'decode' => true,
                'encode' => false,
                'label' => 'Wing Commander III movie',
            ],
            [
                'extension' => 'webm',
                'decode' => true,
                'encode' => true,
                'label' => 'WebM',
            ],
            [
                'extension' => 'webm_chunk',
                'decode' => false,
                'encode' => true,
                'label' => 'WebM Chunk Muxer',
            ],
            [
                'extension' => 'webm_dash_manifest',
                'decode' => true,
                'encode' => true,
                'label' => 'WebM DASH Manifest',
            ],
            [
                'extension' => 'webp',
                'decode' => false,
                'encode' => true,
                'label' => 'WebP',
            ],
            [
                'extension' => 'webp_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped webp sequence',
            ],
            [
                'extension' => 'webvtt',
                'decode' => true,
                'encode' => true,
                'label' => 'WebVTT subtitle',
            ],
            [
                'extension' => 'wsaud',
                'decode' => true,
                'encode' => false,
                'label' => 'Westwood Studios audio',
            ],
            [
                'extension' => 'wsd',
                'decode' => true,
                'encode' => false,
                'label' => 'Wideband Single-bit Data (WSD)',
            ],
            [
                'extension' => 'wsvqa',
                'decode' => true,
                'encode' => false,
                'label' => 'Westwood Studios VQA',
            ],
            [
                'extension' => 'wtv',
                'decode' => true,
                'encode' => true,
                'label' => 'Windows Television (WTV)',
            ],
            [
                'extension' => 'wv',
                'decode' => true,
                'encode' => true,
                'label' => 'raw WavPack',
            ],
            [
                'extension' => 'wve',
                'decode' => true,
                'encode' => false,
                'label' => 'Psion 3 audio',
            ],
            [
                'extension' => 'x11grab',
                'decode' => true,
                'encode' => false,
                'label' => 'X11 screen capture, using XCB',
            ],
            [
                'extension' => 'xa',
                'decode' => true,
                'encode' => false,
                'label' => 'Maxis XA',
            ],
            [
                'extension' => 'xbin',
                'decode' => true,
                'encode' => false,
                'label' => 'eXtended BINary text (XBIN)',
            ],
            [
                'extension' => 'xmv',
                'decode' => true,
                'encode' => false,
                'label' => 'Microsoft XMV',
            ],
            [
                'extension' => 'xpm_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped xpm sequence',
            ],
            [
                'extension' => 'xv',
                'decode' => false,
                'encode' => true,
                'label' => 'XV (XVideo) output device',
            ],
            [
                'extension' => 'xvag',
                'decode' => true,
                'encode' => false,
                'label' => 'Sony PS3 XVAG',
            ],
            [
                'extension' => 'xwd_pipe',
                'decode' => true,
                'encode' => false,
                'label' => 'piped xwd sequence',
            ],
            [
                'extension' => 'xwma',
                'decode' => true,
                'encode' => false,
                'label' => 'Microsoft xWMA',
            ],
            [
                'extension' => 'yop',
                'decode' => true,
                'encode' => false,
                'label' => 'Psygnosis YOP',
            ],
            [
                'extension' => 'yuv4mpegpipe',
                'decode' => true,
                'encode' => true,
                'label' => 'YUV4MPEG pipe',
            ],
        ];
    }
}
