<?php

namespace OCA\AutomaticMediaEncoder\Constants;

class VideoFormats
{
    public const FROM = [
        [
            ['format' => '012v', 'label' => 'Uncompressed 4:2:2 10-bit', 'compression' => 'lossless'],
            ['format' => '4xm', 'label' => '4X Movie', 'compression' => 'lossy'],
            ['format' => '8bps', 'label' => 'QuickTime 8BPS video', 'compression' => 'lossless'],
            ['format' => 'aasc', 'label' => 'Autodesk RLE', 'compression' => 'lossless'],
            ['format' => 'agm', 'label' => 'Amuse Graphics Movie', 'compression' => 'lossy'],
            ['format' => 'aic', 'label' => 'Apple Intermediate Codec', 'compression' => 'lossy'],
            ['format' => 'alias_pix', 'label' => 'Alias/Wavefront PIX image', 'compression' => 'lossless'],
            ['format' => 'amv', 'label' => 'AMV Video', 'compression' => 'lossy'],
            ['format' => 'anm', 'label' => 'Deluxe Paint Animation', 'compression' => 'lossy'],
            ['format' => 'ansi', 'label' => 'ASCII/ANSI art', 'compression' => 'lossy'],
            ['format' => 'apng', 'label' => 'APNG (Animated Portable Network Graphics) image', 'compression' => 'lossless'],
            ['format' => 'arbc', 'label' => 'Gryphon\'s Anim Compressor', 'compression' => 'lossy'],
            ['format' => 'asv1', 'label' => 'ASUS V1', 'compression' => 'lossy'],
            ['format' => 'asv2', 'label' => 'ASUS V2', 'compression' => 'lossy'],
            ['format' => 'aura', 'label' => 'Auravision AURA', 'compression' => 'lossy'],
            ['format' => 'aura2', 'label' => 'Auravision Aura 2', 'compression' => 'lossy'],
            ['format' => 'av1', 'label' => 'Alliance for Open Media AV1 (decoders: libaom-av1 ) (encoders: libaom-av1 )', 'compression' => 'lossy'],
            ['format' => 'avrn', 'label' => 'Avid AVI Codec', 'compression' => NULL],
            ['format' => 'avrp', 'label' => 'Avid 1:1 10-bit RGB Packer', 'compression' => 'lossless'],
            ['format' => 'avs', 'label' => 'AVS (Audio Video Standard) video', 'compression' => 'lossy'],
            ['format' => 'avui', 'label' => 'Avid Meridien Uncompressed', 'compression' => 'lossless'],
            ['format' => 'ayuv', 'label' => 'Uncompressed packed MS 4:4:4:4', 'compression' => 'lossless'],
            ['format' => 'bethsoftvid', 'label' => 'Bethesda VID video', 'compression' => 'lossy'],
            ['format' => 'bfi', 'label' => 'Brute Force & Ignorance', 'compression' => 'lossy'],
            ['format' => 'binkvideo', 'label' => 'Bink video', 'compression' => 'lossy'],
            ['format' => 'bintext', 'label' => 'Binary text', 'compression' => NULL],
            ['format' => 'bitpacked', 'label' => 'Bitpacked', 'compression' => 'lossless'],
            ['format' => 'bmp', 'label' => 'BMP (Windows and OS/2 bitmap)', 'compression' => 'lossless'],
            ['format' => 'bmv_video', 'label' => 'Discworld II BMV video', 'compression' => 'lossless'],
            ['format' => 'brender_pix', 'label' => 'BRender PIX image', 'compression' => 'lossless'],
            ['format' => 'c93', 'label' => 'Interplay C93', 'compression' => 'lossy'],
            ['format' => 'cavs', 'label' => 'Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile)', 'compression' => 'lossy'],
            ['format' => 'cdgraphics', 'label' => 'CD Graphics video', 'compression' => 'lossy'],
            ['format' => 'cdxl', 'label' => 'Commodore CDXL video', 'compression' => 'lossy'],
            ['format' => 'cfhd', 'label' => 'Cineform HD', 'compression' => 'lossy'],
            ['format' => 'cinepak', 'label' => 'Cinepak', 'compression' => 'lossy'],
            ['format' => 'clearvideo', 'label' => 'Iterated Systems ClearVideo', 'compression' => 'lossy'],
            ['format' => 'cljr', 'label' => 'Cirrus Logic AccuPak', 'compression' => 'lossy'],
            ['format' => 'cllc', 'label' => 'Canopus Lossless Codec', 'compression' => 'lossless'],
            ['format' => 'cmv', 'label' => 'Electronic Arts CMV video (decoders: eacmv )', 'compression' => 'lossy'],
            ['format' => 'cpia', 'label' => 'CPiA video format', 'compression' => NULL],
            ['format' => 'cscd', 'label' => 'CamStudio (decoders: camstudio )', 'compression' => 'lossless'],
            ['format' => 'cyuv', 'label' => 'Creative YUV (CYUV)', 'compression' => 'lossy'],
            ['format' => 'dds', 'label' => 'DirectDraw Surface image decoder', 'compression' => 'lossy'],
            ['format' => 'dfa', 'label' => 'Chronomaster DFA', 'compression' => 'lossy'],
            ['format' => 'dirac', 'label' => 'Dirac (encoders: vc2 )', 'compression' => 'lossy'],
            ['format' => 'dnxhd', 'label' => 'VC3/DNxHD', 'compression' => 'lossy'],
            ['format' => 'dpx', 'label' => 'DPX (Digital Picture Exchange) image', 'compression' => 'lossless'],
            ['format' => 'dsicinvideo', 'label' => 'Delphine Software International CIN video', 'compression' => 'lossy'],
            ['format' => 'dvvideo', 'label' => 'DV (Digital Video)', 'compression' => 'lossy'],
            ['format' => 'dxa', 'label' => 'Feeble Files/ScummVM DXA', 'compression' => 'lossless'],
            ['format' => 'dxtory', 'label' => 'Dxtory', 'compression' => 'lossless'],
            ['format' => 'dxv', 'label' => 'Resolume DXV', 'compression' => 'lossy'],
            ['format' => 'escape124', 'label' => 'Escape 124', 'compression' => 'lossy'],
            ['format' => 'escape130', 'label' => 'Escape 130', 'compression' => 'lossy'],
            ['format' => 'exr', 'label' => 'OpenEXR image', 'compression' => 'lossy'],
            ['format' => 'ffv1', 'label' => 'FFmpeg video codec #1', 'compression' => 'lossless'],
            ['format' => 'ffvhuff', 'label' => 'Huffyuv FFmpeg variant', 'compression' => 'lossless'],
            ['format' => 'fic', 'label' => 'Mirillis FIC', 'compression' => 'lossy'],
            ['format' => 'fits', 'label' => 'FITS (Flexible Image Transport System)', 'compression' => 'lossless'],
            ['format' => 'flashsv', 'label' => 'Flash Screen Video v1', 'compression' => 'lossless'],
            ['format' => 'flashsv2', 'label' => 'Flash Screen Video v2', 'compression' => 'lossy'],
            ['format' => 'flic', 'label' => 'Autodesk Animator Flic video', 'compression' => 'lossless'],
            ['format' => 'flv1', 'label' => 'FLV / Sorenson Spark / Sorenson H.263 (Flash Video) (decoders: flv ) (encoders: flv )', 'compression' => 'lossy'],
            ['format' => 'fmvc', 'label' => 'FM Screen Capture Codec', 'compression' => 'lossless'],
            ['format' => 'fraps', 'label' => 'Fraps', 'compression' => 'lossless'],
            ['format' => 'frwu', 'label' => 'Forward Uncompressed', 'compression' => 'lossless'],
            ['format' => 'g2m', 'label' => 'Go2Meeting', 'compression' => 'lossy'],
            ['format' => 'gdv', 'label' => 'Gremlin Digital Video', 'compression' => 'lossy'],
            ['format' => 'gif', 'label' => 'CompuServe GIF (Graphics Interchange Format)', 'compression' => 'lossless'],
            ['format' => 'h261', 'label' => 'H.261', 'compression' => 'lossy'],
            ['format' => 'h263', 'label' => 'H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2 (decoders: h263 h263_v4l2m2m ) (encoders: h263 h263_v4l2m2m )', 'compression' => 'lossy'],
            ['format' => 'h263i', 'label' => 'Intel H.263', 'compression' => 'lossy'],
            ['format' => 'h263p', 'label' => 'H.263+ / H.263-1998 / H.263 version 2', 'compression' => 'lossy'],
            ['extension' => 'mp4', 'format' => 'h264', 'label' => 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_omx h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )', 'compression' => 'lossy'],
            ['format' => 'hap', 'label' => 'Vidvox Hap', 'compression' => 'lossy'],
            ['format' => 'hevc', 'label' => 'H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_v4l2m2m hevc_cuvid ) (encoders: libx265 nvenc_hevc hevc_nvenc hevc_v4l2m2m hevc_vaapi )', 'compression' => 'lossy'],
            ['format' => 'hnm4video', 'label' => 'HNM 4 video', 'compression' => 'lossy'],
            ['format' => 'hq_hqa', 'label' => 'Canopus HQ/HQA', 'compression' => 'lossy'],
            ['format' => 'hqx', 'label' => 'Canopus HQX', 'compression' => 'lossy'],
            ['format' => 'huffyuv', 'label' => 'HuffYUV', 'compression' => 'lossless'],
            ['format' => 'hymt', 'label' => 'HuffYUV MT', 'compression' => 'lossless'],
            ['format' => 'idcin', 'label' => 'id Quake II CIN video (decoders: idcinvideo )', 'compression' => 'lossy'],
            ['format' => 'idf', 'label' => 'iCEDraw text', 'compression' => NULL],
            ['format' => 'iff_ilbm', 'label' => 'IFF ACBM/ANIM/DEEP/ILBM/PBM/RGB8/RGBN (decoders: iff )', 'compression' => 'lossy'],
            ['format' => 'imm4', 'label' => 'Infinity IMM4', 'compression' => 'lossy'],
            ['format' => 'indeo2', 'label' => 'Intel Indeo 2', 'compression' => 'lossy'],
            ['format' => 'indeo3', 'label' => 'Intel Indeo 3', 'compression' => 'lossy'],
            ['format' => 'indeo4', 'label' => 'Intel Indeo Video Interactive 4', 'compression' => 'lossy'],
            ['format' => 'indeo5', 'label' => 'Intel Indeo Video Interactive 5', 'compression' => 'lossy'],
            ['format' => 'interplayvideo', 'label' => 'Interplay MVE video', 'compression' => 'lossy'],
            ['format' => 'jpeg2000', 'label' => 'JPEG 2000 (decoders: jpeg2000 libopenjpeg ) (encoders: jpeg2000 libopenjpeg )', 'compression' => 'lossy'],
            ['format' => 'jpegls', 'label' => 'JPEG-LS', 'compression' => 'lossy'],
            ['format' => 'jv', 'label' => 'Bitmap Brothers JV video', 'compression' => 'lossy'],
            ['format' => 'kgv1', 'label' => 'Kega Game Video', 'compression' => 'lossy'],
            ['format' => 'kmvc', 'label' => 'Karl Morton\'s video codec', 'compression' => 'lossy'],
            ['format' => 'lagarith', 'label' => 'Lagarith lossless', 'compression' => 'lossless'],
            ['format' => 'loco', 'label' => 'LOCO', 'compression' => 'lossless'],
            ['format' => 'lscr', 'label' => 'LEAD Screen Capture', 'compression' => 'lossy'],
            ['format' => 'm101', 'label' => 'Matrox Uncompressed SD', 'compression' => 'lossless'],
            ['format' => 'mad', 'label' => 'Electronic Arts Madcow Video (decoders: eamad )', 'compression' => 'lossy'],
            ['format' => 'magicyuv', 'label' => 'MagicYUV video', 'compression' => 'lossless'],
            ['format' => 'mdec', 'label' => 'Sony PlayStation MDEC (Motion DECoder)', 'compression' => 'lossy'],
            ['format' => 'mimic', 'label' => 'Mimic', 'compression' => 'lossy'],
            ['format' => 'mjpeg', 'label' => 'Motion JPEG (decoders: mjpeg mjpeg_cuvid ) (encoders: mjpeg mjpeg_vaapi )', 'compression' => 'lossy'],
            ['format' => 'mjpegb', 'label' => 'Apple MJPEG-B', 'compression' => 'lossy'],
            ['format' => 'mmvideo', 'label' => 'American Laser Games MM Video', 'compression' => 'lossy'],
            ['format' => 'motionpixels', 'label' => 'Motion Pixels video', 'compression' => 'lossy'],
            ['format' => 'mpeg1video', 'label' => 'MPEG-1 video (decoders: mpeg1video mpeg1_v4l2m2m mpeg1_cuvid )', 'compression' => 'lossy'],
            ['format' => 'mpeg2video', 'label' => 'MPEG-2 video (decoders: mpeg2video mpegvideo mpeg2_v4l2m2m mpeg2_cuvid ) (encoders: mpeg2video mpeg2_vaapi )', 'compression' => 'lossy'],
            ['format' => 'mpeg4', 'label' => 'MPEG-4 part 2 (decoders: mpeg4 mpeg4_v4l2m2m mpeg4_cuvid ) (encoders: mpeg4 libxvid mpeg4_v4l2m2m )', 'compression' => 'lossy'],
            ['format' => 'msa1', 'label' => 'MS ATC Screen', 'compression' => 'lossy'],
            ['format' => 'mscc', 'label' => 'Mandsoft Screen Capture Codec', 'compression' => 'lossless'],
            ['format' => 'msmpeg4v1', 'label' => 'MPEG-4 part 2 Microsoft variant version 1', 'compression' => 'lossy'],
            ['format' => 'msmpeg4v2', 'label' => 'MPEG-4 part 2 Microsoft variant version 2', 'compression' => 'lossy'],
            ['format' => 'msmpeg4v3', 'label' => 'MPEG-4 part 2 Microsoft variant version 3 (decoders: msmpeg4 ) (encoders: msmpeg4 )', 'compression' => 'lossy'],
            ['format' => 'msrle', 'label' => 'Microsoft RLE', 'compression' => 'lossless'],
            ['format' => 'mss1', 'label' => 'MS Screen 1', 'compression' => 'lossy'],
            ['format' => 'mss2', 'label' => 'MS Windows Media Video V9 Screen', 'compression' => 'lossy'],
            ['format' => 'msvideo1', 'label' => 'Microsoft Video 1', 'compression' => 'lossy'],
            ['format' => 'mszh', 'label' => 'LCL (LossLess Codec Library) MSZH', 'compression' => 'lossless'],
            ['format' => 'mts2', 'label' => 'MS Expression Encoder Screen', 'compression' => 'lossy'],
            ['format' => 'mvc1', 'label' => 'Silicon Graphics Motion Video Compressor 1', 'compression' => 'lossy'],
            ['format' => 'mvc2', 'label' => 'Silicon Graphics Motion Video Compressor 2', 'compression' => 'lossy'],
            ['format' => 'mwsc', 'label' => 'MatchWare Screen Capture Codec', 'compression' => 'lossless'],
            ['format' => 'mxpeg', 'label' => 'Mobotix MxPEG video', 'compression' => 'lossy'],
            ['format' => 'nuv', 'label' => 'NuppelVideo/RTJPEG', 'compression' => 'lossy'],
            ['format' => 'paf_video', 'label' => 'Amazing Studio Packed Animation File Video', 'compression' => 'lossy'],
            ['format' => 'pam', 'label' => 'PAM (Portable AnyMap) image', 'compression' => 'lossless'],
            ['format' => 'pbm', 'label' => 'PBM (Portable BitMap) image', 'compression' => 'lossless'],
            ['format' => 'pcx', 'label' => 'PC Paintbrush PCX image', 'compression' => 'lossless'],
            ['format' => 'pgm', 'label' => 'PGM (Portable GrayMap) image', 'compression' => 'lossless'],
            ['format' => 'pgmyuv', 'label' => 'PGMYUV (Portable GrayMap YUV) image', 'compression' => 'lossless'],
            ['format' => 'pictor', 'label' => 'Pictor/PC Paint', 'compression' => 'lossy'],
            ['format' => 'pixlet', 'label' => 'Apple Pixlet', 'compression' => 'lossy'],
            ['format' => 'png', 'label' => 'PNG (Portable Network Graphics) image', 'compression' => 'lossless'],
            ['format' => 'ppm', 'label' => 'PPM (Portable PixelMap) image', 'compression' => 'lossless'],
            ['format' => 'prores', 'label' => 'Apple ProRes (iCodec Pro) (encoders: prores prores_aw prores_ks )', 'compression' => 'lossy'],
            ['format' => 'prosumer', 'label' => 'Brooktree ProSumer Video', 'compression' => 'lossy'],
            ['format' => 'psd', 'label' => 'Photoshop PSD file', 'compression' => 'lossless'],
            ['format' => 'ptx', 'label' => 'V.Flash PTX image', 'compression' => 'lossy'],
            ['format' => 'qdraw', 'label' => 'Apple QuickDraw', 'compression' => 'lossless'],
            ['format' => 'qpeg', 'label' => 'Q-team QPEG', 'compression' => 'lossy'],
            ['format' => 'qtrle', 'label' => 'QuickTime Animation (RLE) video', 'compression' => 'lossless'],
            ['format' => 'r10k', 'label' => 'AJA Kona 10-bit RGB Codec', 'compression' => 'lossless'],
            ['format' => 'r210', 'label' => 'Uncompressed RGB 10-bit', 'compression' => 'lossless'],
            ['format' => 'rasc', 'label' => 'RemotelyAnywhere Screen Capture', 'compression' => 'lossy'],
            ['format' => 'rawvideo', 'label' => 'raw video', 'compression' => 'lossless'],
            ['format' => 'rl2', 'label' => 'RL2 video', 'compression' => 'lossy'],
            ['format' => 'roq', 'label' => 'id RoQ video (decoders: roqvideo ) (encoders: roqvideo )', 'compression' => 'lossy'],
            ['format' => 'rpza', 'label' => 'QuickTime video (RPZA)', 'compression' => 'lossy'],
            ['format' => 'rscc', 'label' => 'innoHeim/Rsupport Screen Capture Codec', 'compression' => 'lossless'],
            ['format' => 'rv10', 'label' => 'RealVideo 1.0', 'compression' => 'lossy'],
            ['format' => 'rv20', 'label' => 'RealVideo 2.0', 'compression' => 'lossy'],
            ['format' => 'rv30', 'label' => 'RealVideo 3.0', 'compression' => 'lossy'],
            ['format' => 'rv40', 'label' => 'RealVideo 4.0', 'compression' => 'lossy'],
            ['format' => 'sanm', 'label' => 'LucasArts SANM/SMUSH video', 'compression' => 'lossy'],
            ['format' => 'scpr', 'label' => 'ScreenPressor', 'compression' => 'lossy'],
            ['format' => 'screenpresso', 'label' => 'Screenpresso', 'compression' => 'lossless'],
            ['format' => 'sgi', 'label' => 'SGI image', 'compression' => 'lossless'],
            ['format' => 'sgirle', 'label' => 'SGI RLE 8-bit', 'compression' => 'lossless'],
            ['format' => 'sheervideo', 'label' => 'BitJazz SheerVideo', 'compression' => 'lossless'],
            ['format' => 'smackvideo', 'label' => 'Smacker video (decoders: smackvid )', 'compression' => 'lossy'],
            ['format' => 'smc', 'label' => 'QuickTime Graphics (SMC)', 'compression' => 'lossy'],
            ['format' => 'smvjpeg', 'label' => 'Sigmatel Motion Video', 'compression' => NULL],
            ['format' => 'snow', 'label' => 'Snow', 'compression' => 'lossy'],
            ['format' => 'sp5x', 'label' => 'Sunplus JPEG (SP5X)', 'compression' => 'lossy'],
            ['format' => 'speedhq', 'label' => 'NewTek SpeedHQ', 'compression' => 'lossy'],
            ['format' => 'srgc', 'label' => 'Screen Recorder Gold Codec', 'compression' => 'lossless'],
            ['format' => 'sunrast', 'label' => 'Sun Rasterfile image', 'compression' => 'lossless'],
            ['format' => 'svg', 'label' => 'Scalable Vector Graphics (decoders: librsvg )', 'compression' => 'lossless'],
            ['format' => 'svq1', 'label' => 'Sorenson Vector Quantizer 1 / Sorenson Video 1 / SVQ1', 'compression' => 'lossy'],
            ['format' => 'svq3', 'label' => 'Sorenson Vector Quantizer 3 / Sorenson Video 3 / SVQ3', 'compression' => 'lossy'],
            ['format' => 'targa', 'label' => 'Truevision Targa image', 'compression' => 'lossless'],
            ['format' => 'targa_y216', 'label' => 'Pinnacle TARGA CineWave YUV16', 'compression' => 'lossless'],
            ['format' => 'tdsc', 'label' => 'TDSC', 'compression' => 'lossy'],
            ['format' => 'tgq', 'label' => 'Electronic Arts TGQ video (decoders: eatgq )', 'compression' => 'lossy'],
            ['format' => 'tgv', 'label' => 'Electronic Arts TGV video (decoders: eatgv )', 'compression' => 'lossy'],
            ['format' => 'theora', 'label' => 'Theora (encoders: libtheora )', 'compression' => 'lossy'],
            ['format' => 'thp', 'label' => 'Nintendo Gamecube THP video', 'compression' => 'lossy'],
            ['format' => 'tiertexseqvideo', 'label' => 'Tiertex Limited SEQ video', 'compression' => 'lossy'],
            ['format' => 'tiff', 'label' => 'TIFF image', 'compression' => 'lossless'],
            ['format' => 'tmv', 'label' => '8088flex TMV', 'compression' => 'lossy'],
            ['format' => 'tqi', 'label' => 'Electronic Arts TQI video (decoders: eatqi )', 'compression' => 'lossy'],
            ['format' => 'truemotion1', 'label' => 'Duck TrueMotion 1.0', 'compression' => 'lossy'],
            ['format' => 'truemotion2', 'label' => 'Duck TrueMotion 2.0', 'compression' => 'lossy'],
            ['format' => 'truemotion2rt', 'label' => 'Duck TrueMotion 2.0 Real Time', 'compression' => 'lossy'],
            ['format' => 'tscc', 'label' => 'TechSmith Screen Capture Codec (decoders: camtasia )', 'compression' => 'lossless'],
            ['format' => 'tscc2', 'label' => 'TechSmith Screen Codec 2', 'compression' => 'lossy'],
            ['format' => 'txd', 'label' => 'Renderware TXD (TeXture Dictionary) image', 'compression' => 'lossy'],
            ['format' => 'ulti', 'label' => 'IBM UltiMotion (decoders: ultimotion )', 'compression' => 'lossy'],
            ['format' => 'utvideo', 'label' => 'Ut Video', 'compression' => 'lossless'],
            ['format' => 'v210', 'label' => 'Uncompressed 4:2:2 10-bit', 'compression' => 'lossless'],
            ['format' => 'v210x', 'label' => 'Uncompressed 4:2:2 10-bit', 'compression' => 'lossless'],
            ['format' => 'v308', 'label' => 'Uncompressed packed 4:4:4', 'compression' => 'lossless'],
            ['format' => 'v408', 'label' => 'Uncompressed packed QT 4:4:4:4', 'compression' => 'lossless'],
            ['format' => 'v410', 'label' => 'Uncompressed 4:4:4 10-bit', 'compression' => 'lossless'],
            ['format' => 'vb', 'label' => 'Beam Software VB', 'compression' => 'lossy'],
            ['format' => 'vble', 'label' => 'VBLE Lossless Codec', 'compression' => 'lossless'],
            ['format' => 'vc1', 'label' => 'SMPTE VC-1 (decoders: vc1 vc1_v4l2m2m vc1_cuvid )', 'compression' => 'lossy'],
            ['format' => 'vc1image', 'label' => 'Windows Media Video 9 Image v2', 'compression' => 'lossy'],
            ['format' => 'vcr1', 'label' => 'ATI VCR1', 'compression' => 'lossy'],
            ['format' => 'vixl', 'label' => 'Miro VideoXL (decoders: xl )', 'compression' => 'lossy'],
            ['format' => 'vmdvideo', 'label' => 'Sierra VMD video', 'compression' => 'lossy'],
            ['format' => 'vmnc', 'label' => 'VMware Screen Codec / VMware Video', 'compression' => 'lossless'],
            ['format' => 'vp3', 'label' => 'On2 VP3', 'compression' => 'lossy'],
            ['format' => 'vp4', 'label' => 'On2 VP4', 'compression' => 'lossy'],
            ['format' => 'vp5', 'label' => 'On2 VP5', 'compression' => 'lossy'],
            ['format' => 'vp6', 'label' => 'On2 VP6', 'compression' => 'lossy'],
            ['format' => 'vp6a', 'label' => 'On2 VP6 (Flash version, with alpha channel)', 'compression' => 'lossy'],
            ['format' => 'vp6f', 'label' => 'On2 VP6 (Flash version)', 'compression' => 'lossy'],
            ['format' => 'vp7', 'label' => 'On2 VP7', 'compression' => 'lossy'],
            ['format' => 'vp8', 'label' => 'On2 VP8 (decoders: vp8 vp8_v4l2m2m libvpx vp8_cuvid ) (encoders: libvpx vp8_v4l2m2m vp8_vaapi )', 'compression' => 'lossy'],
            ['format' => 'vp9', 'label' => 'Google VP9 (decoders: vp9 vp9_v4l2m2m libvpx-vp9 vp9_cuvid ) (encoders: libvpx-vp9 vp9_vaapi )', 'compression' => 'lossy'],
            ['format' => 'wcmv', 'label' => 'WinCAM Motion Video', 'compression' => 'lossless'],
            ['format' => 'webp', 'label' => 'WebP (encoders: libwebp_anim libwebp )', 'compression' => 'lossy'],
            ['format' => 'wmv1', 'label' => 'Windows Media Video 7', 'compression' => 'lossy'],
            ['format' => 'wmv2', 'label' => 'Windows Media Video 8', 'compression' => 'lossy'],
            ['format' => 'wmv3', 'label' => 'Windows Media Video 9', 'compression' => 'lossy'],
            ['format' => 'wmv3image', 'label' => 'Windows Media Video 9 Image', 'compression' => 'lossy'],
            ['format' => 'wnv1', 'label' => 'Winnov WNV1', 'compression' => 'lossy'],
            ['format' => 'wrapped_avframe', 'label' => 'AVFrame to AVPacket passthrough', 'compression' => 'lossless'],
            ['format' => 'ws_vqa', 'label' => 'Westwood Studios VQA (Vector Quantized Animation) video (decoders: vqavideo )', 'compression' => 'lossy'],
            ['format' => 'xan_wc3', 'label' => 'Wing Commander III / Xan', 'compression' => 'lossy'],
            ['format' => 'xan_wc4', 'label' => 'Wing Commander IV / Xxan', 'compression' => 'lossy'],
            ['format' => 'xbin', 'label' => 'eXtended BINary text', 'compression' => NULL],
            ['format' => 'xbm', 'label' => 'XBM (X BitMap) image', 'compression' => 'lossless'],
            ['format' => 'xface', 'label' => 'X-face image', 'compression' => 'lossy'],
            ['format' => 'xpm', 'label' => 'XPM (X PixMap) image', 'compression' => 'lossless'],
            ['format' => 'xwd', 'label' => 'XWD (X Window Dump) image', 'compression' => 'lossless'],
            ['format' => 'y41p', 'label' => 'Uncompressed YUV 4:1:1 12-bit', 'compression' => 'lossless'],
            ['format' => 'ylc', 'label' => 'YUY2 Lossless Codec', 'compression' => 'lossless'],
            ['format' => 'yop', 'label' => 'Psygnosis YOP Video', 'compression' => 'lossy'],
            ['format' => 'yuv4', 'label' => 'Uncompressed packed 4:2:0', 'compression' => 'lossless'],
            ['format' => 'zerocodec', 'label' => 'ZeroCodec Lossless Video', 'compression' => 'lossless'],
            ['format' => 'zlib', 'label' => 'LCL (LossLess Codec Library) ZLIB', 'compression' => 'lossless'],
            ['format' => 'zmbv', 'label' => 'Zip Motion Blocks Video', 'compression' => 'lossless']
        ]
    ];

    public const TO = [];
}
